name: 'Test Terrachops Action'

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: write
  deployments: write

jobs:
  test:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Terrachops
        uses: ./action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
